# Site settings
title: Aurora User Docs
baseurl: /documentation

collections:
  docs:
    output: true

defaults:
  - scope:
      path: ""
      type: docs
    values:
      layout: doc

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-avatar
  - jekyll-relative-links
  - jemoji

relative_links:
  enabled: true
  collections: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock