# Site settings
title: Aurora User Docs
baseurl:

collections:
  docs:
    output: true

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-avatar

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock