baseURL = "//wibble199.github.io/Aurora-Docs/"
languageCode = "en-US"
title = "Aurora User Docs"
theme = "aurora"
disableKinds = ["taxonomy", "taxonomyTerm"]
canonifyURLs = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe= true
