baseURL = "https://www.project-aurora.com/Docs/"
authority = "www.project-aurora.com/Docs/"
languageCode = "en-US"
title = "Aurora User Docs"
theme = "aurora"
disableKinds = ["taxonomy"]
canonifyURLs = true
enableGitInfo = true

[services]
  [services.googleAnalytics]
    id = 'G-74PP2Q060B'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1
  [markup.goldmark.renderer]
    unsafe = true

[module]
[[module.imports]]
path = 'github.com/hugomods/images'
